In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
'/content/drive/myDrive/COLAB NOTEBOOKS'

'/content/drive/myDrive/COLAB NOTEBOOKS'

In [ ]:
import pandas as pd
pd.read_csv("/content/drive/MyDrive/Diabetes Missing Data.csv")

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,NaN,36.8,0.340,27,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0
766,1,126.0,60.0,NaN,NaN,30.1,0.349,47,1
767,1,93.0,70.0,31.0,NaN,30.4,0.315,23,0

In [ ]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Diabetes Missing Data.csv")
df

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,NaN,36.8,0.340,27,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0
766,1,126.0,60.0,NaN,NaN,30.1,0.349,47,1
767,1,93.0,70.0,31.0,NaN,30.4,0.315,23,0

In [ ]:
df.head()

   Pregnant  Diabetes_Pedigree   Age  Class
0       6.0              0.627  50.0    1.0
1       1.0              0.351  31.0    0.0
2       8.0              0.672  32.0    1.0
3       1.0              0.167  21.0    0.0
4       0.0              2.288  33.0    1.0

In [ ]:
print(df.isnull().sum())

Pregnant               0
Glucose                5
Diastolic_BP          35
Skin_Fold            227
Serum_Insulin        374
BMI                   11
Diabetes_Pedigree      0
Age                    0
Class                  0
dtype: int64

In [ ]:
imputer = SimpleImputer(strategy='mean')
print(imputer)

SimpleImputer()

In [ ]:
df[df.columns] = imputer.fit_transform(df)
df

     Pregnant  Diabetes_Pedigree   Age  Class
0         6.0              0.627  50.0    1.0
1         1.0              0.351  31.0    0.0
2         8.0              0.672  32.0    1.0
3         1.0              0.167  21.0    0.0
4         0.0              2.288  33.0    1.0
..        ...                ...   ...    ...
763      10.0              0.171  63.0    0.0
764       2.0              0.340  27.0    0.0
765       5.0              0.245  30.0    0.0
766       1.0              0.349  47.0    1.0
767       1.0              0.315  23.0    0.0

[768 rows x 4 columns]

In [ ]:
df.to_csv('Diabetes_Cleaned.csv', index=False)
df

     Pregnant  Diabetes_Pedigree   Age  Class
0         6.0              0.627  50.0    1.0
1         1.0              0.351  31.0    0.0
2         8.0              0.672  32.0    1.0
3         1.0              0.167  21.0    0.0
4         0.0              2.288  33.0    1.0
..        ...                ...   ...    ...
763      10.0              0.171  63.0    0.0
764       2.0              0.340  27.0    0.0
765       5.0              0.245  30.0    0.0
766       1.0              0.349  47.0    1.0
767       1.0              0.315  23.0    0.0

[768 rows x 4 columns]